createNamespace: true

controller:
  plugin:
    image:
      pullPolicy: Always
      tag: edge

node:
  plugin:
    image:
      pullPolicy: Always
      tag: edge

nodeSelector:
  node-role.kubernetes.io/control-plane: ""
tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule

storageClass:
  - name: hybrid-data
